irnss:
  parent-folder: /common-view-data

spring:
  datasource:
    url: jdbc:postgresql://192.168.251.111:5432/time-traceability-hasura-qa
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3002
