server:
  servlet:
    context-path: /time-traceability-service
  port: 6002

#  ssl:
#    key-store: keystore.p12
#    key-store-password: tnf_npl
#    key-store-type: PKCS12
#    key-alias: your_alias
spring:
  profiles:
    active: prod
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  data:
    web:
      pageable:
        default-page-size=10:
        max-page-size=50:

