    irnss:
      parent-folder: /home/bharath/files

    spring:
      datasource:
        url: jdbc:postgresql://172.16.15.32:5432/time-traceability-hasura-dev
        username: postgres
        password: postgres
      jpa:
        hibernate:
          ddl-auto: update
#    server:
#      port: 4002
