server:
  servlet:
    context-path: /time-traceability-service
  port: 6003

#  ssl:
#    key-store: keystore.p12
#    key-store-password: tnf_npl
#    key-store-type: PKCS12
#    key-alias: your_alias
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  data:
    web:
      pageable:
        default-page-size=10:
        max-page-size=50:

# Application specific configuration
app:
  scheduler:
    materialized-view:
      enabled: true
      refresh-interval: 3600000  # 1 hour in milliseconds (3600000ms = 60min)
      # Alternative intervals:
      # 1800000 = 30 minutes
      # 900000 = 15 minutes
      # 300000 = 5 minutes

