    irnss:
      parent-folder: C:/Users/sumit/OneDrive/Desktop/projects/data

    spring:
      datasource:
        url: jdbc:postgresql://192.168.1.13:5432/time-traceability-hasura-dev
        username: postgres
        password: postgres
      jpa:
        hibernate:
          ddl-auto: update
#    server:
#      port: 4002
